version: "3"

services:
    nginx:
        image: nginx
        restart: always
        ports:
            - 80:80
        volumes:
            - ./nginx/html:/usr/share/nginx/html
            - ./nginx/conf.d:/etc/nginx/conf.d

        command: >
            /bin/bash -c
            "while :;
            do sleep 6h & wait $${!};
            nginx -t && nginx -s reload;
            done
            & nginx -g 'daemon off;'"

networks:
    default:
        external:
            name: web
