version: "3"

services:
    nginx:
        image: nginx
        env_file: .env
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/html:/usr/share/nginx/html
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot

        # using environment variables in nginx:
        # https://serverfault.com/questions/577370/how-can-i-use-environment-variables-in-nginx-conf
        # escaping variables in docker-compose:
        # https://github.com/docker-library/docs/issues/496#issuecomment-203003827
        command: >
            /bin/bash -c
            "envsubst '$$HOST_DOMAIN $$ALIAS_DOMAINS'
            < /etc/nginx/conf.d/default.conf.template
            > /etc/nginx/conf.d/default.conf
            && while :;
            do sleep 6h & wait $${!};
            nginx -s reload;
            done
            & nginx -g 'daemon off;'"

    certbot:
        image: certbot/certbot
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        entrypoint: >
            /bin/sh -c
            "trap exit TERM;
            while :;
            do certbot renew;
            sleep 12h & wait $${!};
            done;"

networks:
    default:
        external:
            name: web
